// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmmbqlywtggvvknmylsb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImttbWJxbHl3dGdndnZrbm15bHNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMjE4NDksImV4cCI6MjA2NzU5Nzg0OX0._frHkSlQ250T16lbVCcBWg77dR0wc58vc77KVAf9JSM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});